### ISSUE TITLE
Library documentation?

### ISSUE THREAD

**Issue by aptonline** [derkalle4/python3-idotmatrix-library#2]
I can't only find code examples of the Chronograph feature, are there plans to expand on this as part of a Wiki?  I'm looking to try the image feature.  Should I use the idotmatrix-client at the time?

Thanks

**Comment by derkalle4** [comment]
Hi @aptonline,

I have many plans but suffer from long COVID so currently there are much opportunities to make this repository here a better place. The library is the foundation of the client itself. So the client currently does use this library. However, if you just want to try it out simply use the client for now. If you want to write your own program and add the ability to connect to the device and send it all kinds of data, then use the library :)

https://github.com/derkalle4/python3-idotmatrix-client

Kind Regards,
Kalle

**Comment by derkalle4** [comment]
Btw you can simply look into the modules folder here https://github.com/derkalle4/python3-idotmatrix-library/tree/main/idotmatrix/modules to adapt the example of the Chronograph for the other functionalities :)

**Comment by aptonline** [comment]
Thanks for the reply and sorry to hear you have long covid 😟. I’ll take a look at the modules and try and work it out. I’m thinking of putting together a Mac app to control the display so your library would be very helpful.

thanks again and hope you manage to keep the project going.

**Comment by derkalle4** [comment]
@aptonline no worries, it is getting better month to month but still is not good and a long way to go to have my old 100% back. I am alive and can work on my side projects from time to time. Better than nothing :)

Having a mac app sounds nice! If you use my library please update it with your findings or provide some hints and I can have a look into it. there's still much to do and a load of bugs to tackle :D 

I'll close this issue but if you have anything further just re-open it or create a new one

**Comment by aviwad** [comment]
@aptonline I'm working on a macOS app for this too! I'm building a menubar application in SwiftUI. Curious to see if you've made any progress? Are you planning to use this Python library? I'm planning to use this for inspiration and then do the same with Swift + CoreBluetooth
