### ISSUE TITLE
"Light Effect" support

### ISSUE THREAD

**Issue by aviwad** [derkalle4/python3-idotmatrix-library#4]
Hey. The official iDotMatrix app has support for "Light effects", which is a set of 5 effects wherein you can set multiple colours and the colours keeps animating. A screen recording from the app is attached. I will try to decompile the Android app and figure it out myself, but if you have any pointers (such as how you managed to decompile and figure out a large majority of the features), that would be of great assistance. Thanks a lot 😄 

https://github.com/user-attachments/assets/eb3d7473-7d83-4cf4-9653-110844594fbb

**Comment by ellensp** [comment]
The "Light Effect" bluetooth commands seem to be of this format from monitoring the app traffic.

This example is effect 0 with 7 colours

```
1c 00 03 02 00 5a 07 7f 00 00 7f 51 00 7f 7f 00 00 7f 00 00 00 7f 7f 00 7f 7f 7f 7f
|           |     |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
|           |     |  R1 G1 B1 R2 G2 B2 R3 G3 B3 R4 G4 B4 R5 G5 B5 R6 G6 B6 R7 G7 B7
|           |     ^count (RGB tupples) colours 2-7 
|           ^effect number 0-6
^count. full packet size inducing the count byte starting at 1
```

This example is effect 1 with 2 colours

```
0d 00 03 02 01 5a 02 7f 00 7f 7f 00 00
|           |     |  |  |  |  |  |  |
|           |     |  R1 G1 B1 R2 G2 B2
|           |     ^count (RGB tupples) colours 2-7 
|           ^effect number 0-6
^count. full packet size inducing the count byte starting at 1
```

The effects are:  (these are just my descriptions) 
0 graduated horizontal rainbow 
1 random coloured pixels on black
2 random white pixels on changing background
3 vertical rainbow
4 diagonal right rainbow  
5 diagonal left rainbow, on black background
6 random coloured pixels

**Comment by ellensp** [comment]
I have created a PR to add light effect support to this library.

**Comment by aviwad** [comment]
Wow this is awesome.

**Comment by derkalle4** [comment]
@ellensp @aviwad its deployed :) -thank you very much! Sorry for the delay. Feel free to mention me directly. every time something important happens. I do not want to cause unnecessary delays
